// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZy1BDKXvsK9zRxJmtMRM_fVylyG4SrJQ',
    appId: '1:1013266979055:web:be39d87abb9f981216e31a',
    messagingSenderId: '1013266979055',
    projectId: 'myloginapplication-734a7',
    authDomain: 'myloginapplication-734a7.firebaseapp.com',
    storageBucket: 'myloginapplication-734a7.appspot.com',
    measurementId: 'G-PS4FKHM3YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrdPey7RAnaChPxU1gTvRLvKPPGDa-GsA',
    appId: '1:1013266979055:android:84f5f1729aceeba116e31a',
    messagingSenderId: '1013266979055',
    projectId: 'myloginapplication-734a7',
    storageBucket: 'myloginapplication-734a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcu4rpajNaScKYWmGsvsk0A0Zc29W8hHY',
    appId: '1:1013266979055:ios:b3d68bccc3c1372f16e31a',
    messagingSenderId: '1013266979055',
    projectId: 'myloginapplication-734a7',
    storageBucket: 'myloginapplication-734a7.appspot.com',
    iosClientId: '1013266979055-bg04ks3df7t18nuhsmccjnsnmn873nji.apps.googleusercontent.com',
    iosBundleId: 'com.example.myLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcu4rpajNaScKYWmGsvsk0A0Zc29W8hHY',
    appId: '1:1013266979055:ios:b3d68bccc3c1372f16e31a',
    messagingSenderId: '1013266979055',
    projectId: 'myloginapplication-734a7',
    storageBucket: 'myloginapplication-734a7.appspot.com',
    iosClientId: '1013266979055-bg04ks3df7t18nuhsmccjnsnmn873nji.apps.googleusercontent.com',
    iosBundleId: 'com.example.myLoginApp',
  );
}
